# Generated by Django 5.1.4 on 2026-06-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='文本答案')),
                ('answer_number', models.FloatField(blank=True, null=True, verbose_name='数值答案')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='answers/', verbose_name='文件答案')),
                ('answer_json', models.JSONField(blank=True, null=True, verbose_name='JSON 答案')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_info', models.JSONField(blank=True, default=dict, verbose_name='答卷人信息')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('submit_ip', models.GenericIPAddressField(verbose_name='提交 IP')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='填写用时(秒)')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'db_table': 'submissions',
                'ordering': ['-submit_time'],
            },
        ),
    ]
