# Generated by Django 5.1.4 on 2026-06-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='total_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='总分'),
        ),
    ]
