# Generated by Django 5.1.4 on 2026-06-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('radio', '单选题'), ('checkbox', '多选题'), ('text', '填空题'), ('textarea', '多行填空题'), ('multi_text', '多项填空题'), ('dropdown', '下拉单选题'), ('rating', '评分题'), ('ranking', '排序题'), ('date', '日期题'), ('time', '时间题'), ('file_upload', '文件上传题'), ('page_break', '分页'), ('section_break', '分段'), ('scale', '量表题'), ('slider', '滑块题'), ('image_radio', '图片单选题'), ('image_checkbox', '图片多选题'), ('cascade', '级联题'), ('signature', '签名题'), ('location', '定位题'), ('matrix_radio', '矩阵单选题'), ('matrix_checkbox', '矩阵多选题'), ('matrix_rating', '矩阵评分题'), ('matrix_text', '矩阵填空题'), ('matrix_scale', '矩阵量表题'), ('matrix_slider', '矩阵滑块题'), ('matrix_numeric', '矩阵数值题'), ('divider', '分割线'), ('image_upload', '图片上传'), ('image_carousel', '图片轮播'), ('screening', '甄别题'), ('drawing', '绘图题'), ('map', '地图组件'), ('matrix_dropdown', '矩阵下拉题'), ('matrix_combo', '矩阵组合题'), ('matrix_auto_inc', '矩阵自增题')], max_length=30, verbose_name='题目类型')),
                ('title', models.CharField(max_length=1000, verbose_name='题目标题')),
                ('is_required', models.BooleanField(default=True, verbose_name='必填')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='排序')),
                ('score', models.IntegerField(default=0, verbose_name='题目分数')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目列表',
                'db_table': 'questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('status', models.SmallIntegerField(choices=[(0, '草稿'), (1, '已发布'), (2, '已关闭')], default=0, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('style', models.JSONField(blank=True, default=dict, verbose_name='样式配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '问卷',
                'verbose_name_plural': '问卷列表',
                'db_table': 'surveys',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='选项名')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('score', models.IntegerField(default=0, verbose_name='选项分值')),
                ('image', models.ImageField(blank=True, null=True, upload_to='options/', verbose_name='选项图片')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项列表',
                'db_table': 'options',
                'ordering': ['order'],
            },
        ),
    ]
