# Generated by Django 5.1.4 on 2026-06-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='题目标题'),
        ),
    ]
