# Generated by Django 5.1.4 on 2026-06-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='选项名'),
        ),
    ]
