# Generated by Django 5.1.4 on 2026-06-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_option_title'),
        ('users', '0004_user_managed_department_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='target_departments',
            field=models.ManyToManyField(blank=True, related_name='targeted_surveys', to='users.department', verbose_name='定向部门'),
        ),
    ]
