# Generated by Django 5.1.4 on 2026-06-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey_target_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
    ]
