# Generated by Django 5.1.4 on 2026-06-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_survey_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='scoring_enabled',
            field=models.BooleanField(default=False, verbose_name='启用评分'),
        ),
    ]
