# Generated by Django 5.1.4 on 2026-06-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_survey_scoring_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='skip_enabled',
            field=models.BooleanField(default=False, verbose_name='启用跳转'),
        ),
    ]
