# Generated by Django 5.1.4 on 2026-06-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, '总管理'), (2, '出题人'), (3, '答题人')], default=3, verbose_name='角色'),
        ),
    ]
