# Generated by Django 5.1.4 on 2026-06-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='users.department', verbose_name='管理的部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, '总管理'), (2, '出题人'), (3, '答题人'), (4, '部门负责人')], default=3, verbose_name='角色'),
        ),
    ]
