# Generated by Django 5.1.4 on 2026-06-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_display_name_user_employee_id_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '未选择'), ('male', '男'), ('female', '女')], default='', max_length=10, verbose_name='性别'),
        ),
    ]
