# Generated by Django 5.1.4 on 2026-06-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, '总管理'), (2, '管理员'), (3, '用户'), (4, '部门负责人')], default=3, verbose_name='角色'),
        ),
    ]
