# Generated by Django 5.1.4 on 2026-06-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('major', '专业'), ('school', '院校'), ('industry', '行业'), ('occupation', '职业'), ('region', '行政区划'), ('common', '常用')], db_index=True, max_length=20, verbose_name='分类')),
                ('label', models.CharField(db_index=True, max_length=200, verbose_name='标签/关键词')),
                ('question_type', models.CharField(max_length=30, verbose_name='题型')),
                ('title', models.CharField(max_length=1000, verbose_name='题目标题')),
                ('options_data', models.JSONField(blank=True, default=list, verbose_name='选项数据')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
                'db_table': 'question_bank',
                'ordering': ['category', 'label'],
            },
        ),
    ]
