# Generated by Django 5.1.4 on 2026-06-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '问卷模板',
                'verbose_name_plural': '问卷模板',
                'db_table': 'survey_templates',
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='TemplateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='选项名')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('score', models.IntegerField(default=0, verbose_name='分值')),
            ],
            options={
                'verbose_name': '模板选项',
                'db_table': 'template_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='题型')),
                ('title', models.CharField(max_length=1000, verbose_name='标题')),
                ('is_required', models.BooleanField(default=True, verbose_name='必填')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
            ],
            options={
                'verbose_name': '模板题目',
                'db_table': 'template_questions',
                'ordering': ['order'],
            },
        ),
    ]
